# Generated by Django 5.1.1 on 2024-09-14 13:29

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(max_length=150)),
                ('group', models.IntegerField()),
                ('days', models.IntegerField()),
                ('nights', models.IntegerField()),
                ('price', models.FloatField()),
                ('date_depart', models.DateTimeField()),
                ('date_return', models.DateTimeField()),
                ('tour_highlight_1', models.CharField(max_length=200)),
                ('tour_highlight_2', models.CharField(max_length=200)),
                ('tour_highlight_3', models.CharField(max_length=200)),
                ('tour_highlight_4', models.CharField(max_length=200)),
                ('tour_highlight_5', models.CharField(max_length=200)),
                ('tour_highlight_6', models.CharField(max_length=200)),
                ('image_1', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[600, 500], upload_to='tours')),
                ('image_2', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[600, 500], upload_to='tours')),
                ('image_3', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[600, 500], upload_to='tours')),
                ('image_4', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[600, 500], upload_to='tours')),
                ('image_5', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[600, 500], upload_to='tours')),
                ('image_6', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[600, 500], upload_to='tours')),
                ('inclusion_1', models.CharField(max_length=100)),
                ('inclusion_2', models.CharField(max_length=100)),
                ('inclusion_3', models.CharField(max_length=100)),
                ('inclusion_4', models.CharField(max_length=100)),
                ('inclusion_5', models.CharField(max_length=100)),
                ('inclusion_6', models.CharField(max_length=100)),
                ('exclusion_1', models.CharField(blank=True, max_length=100, null=True)),
                ('exclusion_2', models.CharField(blank=True, max_length=100, null=True)),
                ('exclusion_3', models.CharField(blank=True, max_length=100, null=True)),
                ('exclusion_4', models.CharField(blank=True, max_length=100, null=True)),
                ('exclusion_5', models.CharField(blank=True, max_length=100, null=True)),
                ('exclusion_6', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(max_length=50)),
                ('day', models.IntegerField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.tour')),
            ],
        ),
    ]
