# Generated by Django 5.1.1 on 2024-09-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='location',
            field=models.CharField(default='abuja', max_length=50),
            preserve_default=False,
        ),
    ]
