# Generated by Django 5.1.1 on 2024-09-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_itinerary_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='discount',
            field=models.IntegerField(default=2, help_text='in %'),
            preserve_default=False,
        ),
    ]
