# Generated by Django 5.1.1 on 2024-09-14 14:57

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_tour_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='image_1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[400, 300], upload_to='itineraries'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='image_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[400, 300], upload_to='itineraries'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='image_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[400, 300], upload_to='itineraries'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='image_4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[400, 300], upload_to='itineraries'),
        ),
    ]
