# Generated by Django 5.1.1 on 2024-09-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_tour_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.IntegerField(),
        ),
    ]
