# Generated by Django 5.1.1 on 2024-09-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_tour_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('duration', models.IntegerField()),
                ('detail_1', models.CharField(max_length=150)),
                ('detail_2', models.CharField(max_length=150)),
                ('detail_3', models.CharField(max_length=150)),
                ('detail_4', models.CharField(max_length=150)),
                ('detail_5', models.CharField(blank=True, max_length=150, null=True)),
                ('detail_6', models.CharField(blank=True, max_length=150, null=True)),
                ('detail_7', models.CharField(blank=True, max_length=150, null=True)),
                ('detail_8', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
