# Generated by Django 5.1.1 on 2024-09-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
