# Generated by Django 5.1.1 on 2024-09-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_visa_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visa',
            name='image',
        ),
    ]
