# Generated by Django 5.1.1 on 2024-09-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0021_remove_visa_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='price',
            field=models.IntegerField(default=500000),
            preserve_default=False,
        ),
    ]
