# Generated by Django 5.1.1 on 2024-09-16 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0025_course_booking_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_booking',
            name='course',
        ),
        migrations.AddField(
            model_name='course_booking',
            name='visa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel.visa'),
            preserve_default=False,
        ),
    ]
