# Generated by Django 5.1.1 on 2024-09-16 16:00

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0026_remove_course_booking_course_course_booking_visa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_booking',
            name='visa',
        ),
        migrations.AddField(
            model_name='course_booking',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel.course'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Visa_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.visa')),
            ],
        ),
    ]
